### ISSUE TITLE
Design 

### ISSUE THREAD

**Issue by andreajaneyee** [khoiphan21/modulo#10]
## Tasks
- [x] Produce a few more design options for data visualisation
    - [x] Notification pop ups
    - [x] Layout options
- [x] Produce moodboard on Pinterest for the interface
- [x] Rough wireframes for company website
