### ISSUE TITLE
MODULO rename

### ISSUE THREAD

**Issue by andreajaneyee** [khoiphan21/modulo#18]
## Tasks
- [x] rename repository to 'Modulo'
- [x] buy ModuloStudio.com.au domain
- [x] rename ourselves on Adapt
- [x] rename Google Drive
- [x] setup gmail
- [ ] come up with logo
